'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100, 100")>  _
        Public Property Panel_POS_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("Panel_POS_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Panel_POS_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("200, 200")>  _
        Public Property Split1_panel1() As Global.System.Drawing.Size
            Get
                Return CType(Me("Split1_panel1"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Split1_panel1") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("140, 80")>  _
        Public ReadOnly Property ButtonCateSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("ButtonCateSize"),Global.System.Drawing.Size)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("140, 80")>  _
        Public ReadOnly Property ButtonItemSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("ButtonItemSize"),Global.System.Drawing.Size)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tahoma, 12pt")>  _
        Public ReadOnly Property ButtonFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("ButtonFont"),Global.System.Drawing.Font)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\sqlexpress;Initial Catalog=ctm_kr;Persist Security Info=True;User I"& _ 
            "D=sa;Password=admin123")>  _
        Public ReadOnly Property ConnectionDB() As String
            Get
                Return CType(Me("ConnectionDB"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property Comport() As String
            Get
                Return CType(Me("Comport"),String)
            End Get
            Set
                Me("Comport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property BillCopies() As Integer
            Get
                Return CType(Me("BillCopies"),Integer)
            End Get
            Set
                Me("BillCopies") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CTM004")>  _
        Public Property QrThaiParNerId() As String
            Get
                Return CType(Me("QrThaiParNerId"),String)
            End Get
            Set
                Me("QrThaiParNerId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Cha Tra Mue")>  _
        Public Property QrThaiParNerName() As String
            Get
                Return CType(Me("QrThaiParNerName"),String)
            End Get
            Set
                Me("QrThaiParNerName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WJ4V6SXA8tk3Kpj0XXY9l8iNBkRtGfCCWr5UE7hy0Y66Pz5SSUSb5vsUSrBCYIr9")>  _
        Public Property QrThaiPartnerSecret() As String
            Get
                Return CType(Me("QrThaiPartnerSecret"),String)
            End Get
            Set
                Me("QrThaiPartnerSecret") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("KB000001518278")>  _
        Public Property QrThaiMerchantId() As String
            Get
                Return CType(Me("QrThaiMerchantId"),String)
            End Get
            Set
                Me("QrThaiMerchantId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PTR0000030")>  _
        Public Property QrAliPartnerId() As String
            Get
                Return CType(Me("QrAliPartnerId"),String)
            End Get
            Set
                Me("QrAliPartnerId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Qxdl5KZfISQFqC1JNzsxzhGDZmecmU9oa4sgfN6oVipR3oX6t2w97UvCQPEh8PDo")>  _
        Public Property QrAliPartnerSecret() As String
            Get
                Return CType(Me("QrAliPartnerSecret"),String)
            End Get
            Set
                Me("QrAliPartnerSecret") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EXT01000250227")>  _
        Public Property QrAliMerchantId() As String
            Get
                Return CType(Me("QrAliMerchantId"),String)
            End Get
            Set
                Me("QrAliMerchantId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("55101944")>  _
        Public Property AliTerminal_id() As String
            Get
                Return CType(Me("AliTerminal_id"),String)
            End Get
            Set
                Me("AliTerminal_id") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("55202387")>  _
        Public Property WechatTerminal_id() As String
            Get
                Return CType(Me("WechatTerminal_id"),String)
            End Get
            Set
                Me("WechatTerminal_id") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("401011796876001")>  _
        Public Property Ali_Sub_MID() As String
            Get
                Return CType(Me("Ali_Sub_MID"),String)
            End Get
            Set
                Me("Ali_Sub_MID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("401011796884001")>  _
        Public Property WeChat_Sub_MID() As String
            Get
                Return CType(Me("WeChat_Sub_MID"),String)
            End Get
            Set
                Me("WeChat_Sub_MID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("hiveup_ctmicon")>  _
        Public Property QrDb_Name() As String
            Get
                Return CType(Me("QrDb_Name"),String)
            End Get
            Set
                Me("QrDb_Name") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Project_CTM.My.MySettings
            Get
                Return Global.Project_CTM.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
