'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class category_th
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.category_th", GetType(category_th).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to อณุญาตให้พิมพ์.
        '''</summary>
        Friend Shared ReadOnly Property allowPrint() As String
            Get
                Return ResourceManager.GetString("allowPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สีปุ่ม.
        '''</summary>
        Friend Shared ReadOnly Property buttonColor() As String
            Get
                Return ResourceManager.GetString("buttonColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รหัสหมวดสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property categoryCode() As String
            Get
                Return ResourceManager.GetString("categoryCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ชื่อหมวดสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property categoryName() As String
            Get
                Return ResourceManager.GetString("categoryName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ชื่อหมวดสินค้า (อังกฤษ).
        '''</summary>
        Friend Shared ReadOnly Property categoryNameEN() As String
            Get
                Return ResourceManager.GetString("categoryNameEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หมวดหมู่สินค้า.
        '''</summary>
        Friend Shared ReadOnly Property categoryProduct() As String
            Get
                Return ResourceManager.GetString("categoryProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เพิ่มข้อมูล.
        '''</summary>
        Friend Shared ReadOnly Property clearText() As String
            Get
                Return ResourceManager.GetString("clearText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ลบข้อมูล.
        '''</summary>
        Friend Shared ReadOnly Property delete() As String
            Get
                Return ResourceManager.GetString("delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ลบรูปภาพ.
        '''</summary>
        Friend Shared ReadOnly Property delimage() As String
            Get
                Return ResourceManager.GetString("delimage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายละเอียด.
        '''</summary>
        Friend Shared ReadOnly Property detail() As String
            Get
                Return ResourceManager.GetString("detail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ส่วนลด.
        '''</summary>
        Friend Shared ReadOnly Property discount() As String
            Get
                Return ResourceManager.GetString("discount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กลุ่ม.
        '''</summary>
        Friend Shared ReadOnly Property groupType() As String
            Get
                Return ResourceManager.GetString("groupType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รูปภาพ.
        '''</summary>
        Friend Shared ReadOnly Property image() As String
            Get
                Return ResourceManager.GetString("image", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เพิ่มเติม.
        '''</summary>
        Friend Shared ReadOnly Property more() As String
            Get
                Return ResourceManager.GetString("more", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวนหลักเลขรหัส.
        '''</summary>
        Friend Shared ReadOnly Property numberic() As String
            Get
                Return ResourceManager.GetString("numberic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ชนิดสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property productType() As String
            Get
                Return ResourceManager.GetString("productType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บันทึก.
        '''</summary>
        Friend Shared ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สีอักษร.
        '''</summary>
        Friend Shared ReadOnly Property TextColor() As String
            Get
                Return ResourceManager.GetString("TextColor", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
