'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class closeshift_th
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.closeshift_th", GetType(closeshift_th).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วัน/เวลา เปิดกะการขาย.
        '''</summary>
        Friend Shared ReadOnly Property _date() As String
            Get
                Return ResourceManager.GetString("date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ปุ่มทำรายการ.
        '''</summary>
        Friend Shared ReadOnly Property _event() As String
            Get
                Return ResourceManager.GetString("event", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บาท.
        '''</summary>
        Friend Shared ReadOnly Property bath() As String
            Get
                Return ResourceManager.GetString("bath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยอดเงินในลิ้นชัก :.
        '''</summary>
        Friend Shared ReadOnly Property cash() As String
            Get
                Return ResourceManager.GetString("cash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เงินสด.
        '''</summary>
        Friend Shared ReadOnly Property cash_() As String
            Get
                Return ResourceManager.GetString("cash_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เงินทอน : .
        '''</summary>
        Friend Shared ReadOnly Property change() As String
            Get
                Return ResourceManager.GetString("change", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ปิดกะการขาย.
        '''</summary>
        Friend Shared ReadOnly Property closeShift() As String
            Get
                Return ResourceManager.GetString("closeShift", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คัดแยกเงินใหม่.
        '''</summary>
        Friend Shared ReadOnly Property countMoney() As String
            Get
                Return ResourceManager.GetString("countMoney", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ค่าใช้จ่าย :.
        '''</summary>
        Friend Shared ReadOnly Property expenses() As String
            Get
                Return ResourceManager.GetString("expenses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ขาด/เกิน :.
        '''</summary>
        Friend Shared ReadOnly Property lackExcess() As String
            Get
                Return ResourceManager.GetString("lackExcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คัดแยกเงิน.
        '''</summary>
        Friend Shared ReadOnly Property money() As String
            Get
                Return ResourceManager.GetString("money", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เปิดลิ้นชัก.
        '''</summary>
        Friend Shared ReadOnly Property openDrawer() As String
            Get
                Return ResourceManager.GetString("openDrawer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวน.
        '''</summary>
        Friend Shared ReadOnly Property qty() As String
            Get
                Return ResourceManager.GetString("qty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สรุปยอด.
        '''</summary>
        Friend Shared ReadOnly Property result() As String
            Get
                Return ResourceManager.GetString("result", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยอดรวม.
        '''</summary>
        Friend Shared ReadOnly Property total() As String
            Get
                Return ResourceManager.GetString("total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยอดขายเงินสด : .
        '''</summary>
        Friend Shared ReadOnly Property totalCash() As String
            Get
                Return ResourceManager.GetString("totalCash", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
