'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class customer_en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.customer_en", GetType(customer_en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date..
        '''</summary>
        Friend Shared ReadOnly Property _date() As String
            Get
                Return ResourceManager.GetString("date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Friend Shared ReadOnly Property address() As String
            Get
                Return ResourceManager.GetString("address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bill No..
        '''</summary>
        Friend Shared ReadOnly Property billNo() As String
            Get
                Return ResourceManager.GetString("billNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Code.
        '''</summary>
        Friend Shared ReadOnly Property customerCode() As String
            Get
                Return ResourceManager.GetString("customerCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Data.
        '''</summary>
        Friend Shared ReadOnly Property customerData() As String
            Get
                Return ResourceManager.GetString("customerData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Name.
        '''</summary>
        Friend Shared ReadOnly Property customerName() As String
            Get
                Return ResourceManager.GetString("customerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Type.
        '''</summary>
        Friend Shared ReadOnly Property customerType() As String
            Get
                Return ResourceManager.GetString("customerType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detail.
        '''</summary>
        Friend Shared ReadOnly Property detail() As String
            Get
                Return ResourceManager.GetString("detail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discount.
        '''</summary>
        Friend Shared ReadOnly Property discount() As String
            Get
                Return ResourceManager.GetString("discount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Friend Shared ReadOnly Property email() As String
            Get
                Return ResourceManager.GetString("email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Full Name.
        '''</summary>
        Friend Shared ReadOnly Property fullName() As String
            Get
                Return ResourceManager.GetString("fullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to History Buy.
        '''</summary>
        Friend Shared ReadOnly Property historyBuy() As String
            Get
                Return ResourceManager.GetString("historyBuy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to History Point.
        '''</summary>
        Friend Shared ReadOnly Property historyPoint() As String
            Get
                Return ResourceManager.GetString("historyPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone Number.
        '''</summary>
        Friend Shared ReadOnly Property phoneNumber() As String
            Get
                Return ResourceManager.GetString("phoneNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Point / Unit.
        '''</summary>
        Friend Shared ReadOnly Property pointUnit() As String
            Get
                Return ResourceManager.GetString("pointUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qty.
        '''</summary>
        Friend Shared ReadOnly Property qty() As String
            Get
                Return ResourceManager.GetString("qty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property search() As String
            Get
                Return ResourceManager.GetString("search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend Shared ReadOnly Property total() As String
            Get
                Return ResourceManager.GetString("total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Point.
        '''</summary>
        Friend Shared ReadOnly Property totalPoint() As String
            Get
                Return ResourceManager.GetString("totalPoint", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
