'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class inventory_stock_th
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.inventory_stock_th", GetType(inventory_stock_th).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่.
        '''</summary>
        Friend Shared ReadOnly Property _date() As String
            Get
                Return ResourceManager.GetString("date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เพิ่มรายการ.
        '''</summary>
        Friend Shared ReadOnly Property addItem() As String
            Get
                Return ResourceManager.GetString("addItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เมื่อกรอกข้อมูลเรียบร้อยแล้วกรุณากดปุ่มนี้.
        '''</summary>
        Friend Shared ReadOnly Property Afterfillingout() As String
            Get
                Return ResourceManager.GetString("Afterfillingout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวนรับ.
        '''</summary>
        Friend Shared ReadOnly Property amount() As String
            Get
                Return ResourceManager.GetString("amount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวนที่เหลือ.
        '''</summary>
        Friend Shared ReadOnly Property balance() As String
            Get
                Return ResourceManager.GetString("balance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (ไม่สามารถกรอกข้อมูลได้).
        '''</summary>
        Friend Shared ReadOnly Property Canfillout() As String
            Get
                Return ResourceManager.GetString("Canfillout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เพิ่มสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property clearText() As String
            Get
                Return ResourceManager.GetString("clearText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ทุนรวมภาษี.
        '''</summary>
        Friend Shared ReadOnly Property costaftertax() As String
            Get
                Return ResourceManager.GetString("costaftertax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ทุนก่อนภาษี.
        '''</summary>
        Friend Shared ReadOnly Property costbeforetax() As String
            Get
                Return ResourceManager.GetString("costbeforetax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ต้นทุน.
        '''</summary>
        Friend Shared ReadOnly Property costing() As String
            Get
                Return ResourceManager.GetString("costing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ทุน/หน่วยภาษี.
        '''</summary>
        Friend Shared ReadOnly Property costpercostunit() As String
            Get
                Return ResourceManager.GetString("costpercostunit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ทุน/หน่วย.
        '''</summary>
        Friend Shared ReadOnly Property costperunit() As String
            Get
                Return ResourceManager.GetString("costperunit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่รับเข้า.
        '''</summary>
        Friend Shared ReadOnly Property dateReceipt() As String
            Get
                Return ResourceManager.GetString("dateReceipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ลบข้อมูล.
        '''</summary>
        Friend Shared ReadOnly Property del() As String
            Get
                Return ResourceManager.GetString("del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ใบส่งของเลขที่.
        '''</summary>
        Friend Shared ReadOnly Property deliveryNoteNo() As String
            Get
                Return ResourceManager.GetString("deliveryNoteNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายละเอียด.
        '''</summary>
        Friend Shared ReadOnly Property detail() As String
            Get
                Return ResourceManager.GetString("detail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ราคารวมภาษี.
        '''</summary>
        Friend Shared ReadOnly Property includingVat() As String
            Get
                Return ResourceManager.GetString("includingVat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รหัสสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property productCode() As String
            Get
                Return ResourceManager.GetString("productCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ชื่อสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property productName() As String
            Get
                Return ResourceManager.GetString("productName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประเภทสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property producttype() As String
            Get
                Return ResourceManager.GetString("producttype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวน.
        '''</summary>
        Friend Shared ReadOnly Property qty() As String
            Get
                Return ResourceManager.GetString("qty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายการ.
        '''</summary>
        Friend Shared ReadOnly Property receipt() As String
            Get
                Return ResourceManager.GetString("receipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เลขที่ใบรับสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property receiptNo() As String
            Get
                Return ResourceManager.GetString("receiptNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เลขที่ใบรับสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property Receiptnumber() As String
            Get
                Return ResourceManager.GetString("Receiptnumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รับสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property ReceiptProduct() As String
            Get
                Return ResourceManager.GetString("ReceiptProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บันทึก.
        '''</summary>
        Friend Shared ReadOnly Property save() As String
            Get
                Return ResourceManager.GetString("save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ค้นหา.
        '''</summary>
        Friend Shared ReadOnly Property search() As String
            Get
                Return ResourceManager.GetString("search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ผู้จัดจำหน่าย.
        '''</summary>
        Friend Shared ReadOnly Property seller() As String
            Get
                Return ResourceManager.GetString("seller", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่ใบส่งของ.
        '''</summary>
        Friend Shared ReadOnly Property ShippingDate() As String
            Get
                Return ResourceManager.GetString("ShippingDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สถานะ.
        '''</summary>
        Friend Shared ReadOnly Property status() As String
            Get
                Return ResourceManager.GetString("status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สต๊อก.
        '''</summary>
        Friend Shared ReadOnly Property stock() As String
            Get
                Return ResourceManager.GetString("stock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ราคารวม.
        '''</summary>
        Friend Shared ReadOnly Property subTotal() As String
            Get
                Return ResourceManager.GetString("subTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เบิกสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property TakeProduct() As String
            Get
                Return ResourceManager.GetString("TakeProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เลขที่ใบกำกับภาษี.
        '''</summary>
        Friend Shared ReadOnly Property TaxID() As String
            Get
                Return ResourceManager.GetString("TaxID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ถึงวันที่.
        '''</summary>
        Friend Shared ReadOnly Property todate() As String
            Get
                Return ResourceManager.GetString("todate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ราคารวมภาษี.
        '''</summary>
        Friend Shared ReadOnly Property total() As String
            Get
                Return ResourceManager.GetString("total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ต้นทุนรวมภาษี.
        '''</summary>
        Friend Shared ReadOnly Property totalcostvat() As String
            Get
                Return ResourceManager.GetString("totalcostvat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ราคารวม.
        '''</summary>
        Friend Shared ReadOnly Property totalPrice() As String
            Get
                Return ResourceManager.GetString("totalPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หน่วย.
        '''</summary>
        Friend Shared ReadOnly Property unit() As String
            Get
                Return ResourceManager.GetString("unit", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
