'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class inventory_stock_en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.inventory_stock_en", GetType(inventory_stock_en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Friend Shared ReadOnly Property _date() As String
            Get
                Return ResourceManager.GetString("date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Item.
        '''</summary>
        Friend Shared ReadOnly Property addItem() As String
            Get
                Return ResourceManager.GetString("addItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to After filling out the information, please press this button..
        '''</summary>
        Friend Shared ReadOnly Property Afterfillingout() As String
            Get
                Return ResourceManager.GetString("Afterfillingout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amounts.
        '''</summary>
        Friend Shared ReadOnly Property amount() As String
            Get
                Return ResourceManager.GetString("amount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Balance.
        '''</summary>
        Friend Shared ReadOnly Property balance() As String
            Get
                Return ResourceManager.GetString("balance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can&apos;t Fill Out.
        '''</summary>
        Friend Shared ReadOnly Property Canfillout() As String
            Get
                Return ResourceManager.GetString("Canfillout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear Text.
        '''</summary>
        Friend Shared ReadOnly Property clearText() As String
            Get
                Return ResourceManager.GetString("clearText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost After Tax.
        '''</summary>
        Friend Shared ReadOnly Property costaftertax() As String
            Get
                Return ResourceManager.GetString("costaftertax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost Before Vat.
        '''</summary>
        Friend Shared ReadOnly Property costbeforetax() As String
            Get
                Return ResourceManager.GetString("costbeforetax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost.
        '''</summary>
        Friend Shared ReadOnly Property costing() As String
            Get
                Return ResourceManager.GetString("costing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost/Vat.
        '''</summary>
        Friend Shared ReadOnly Property costpercostunit() As String
            Get
                Return ResourceManager.GetString("costpercostunit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost/Unit.
        '''</summary>
        Friend Shared ReadOnly Property costperunit() As String
            Get
                Return ResourceManager.GetString("costperunit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date Receipt.
        '''</summary>
        Friend Shared ReadOnly Property dateReceipt() As String
            Get
                Return ResourceManager.GetString("dateReceipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property del() As String
            Get
                Return ResourceManager.GetString("del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delivery Note No.
        '''</summary>
        Friend Shared ReadOnly Property deliveryNoteNo() As String
            Get
                Return ResourceManager.GetString("deliveryNoteNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detail.
        '''</summary>
        Friend Shared ReadOnly Property detail() As String
            Get
                Return ResourceManager.GetString("detail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Including Vat.
        '''</summary>
        Friend Shared ReadOnly Property includingVat() As String
            Get
                Return ResourceManager.GetString("includingVat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Code.
        '''</summary>
        Friend Shared ReadOnly Property productCode() As String
            Get
                Return ResourceManager.GetString("productCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Name.
        '''</summary>
        Friend Shared ReadOnly Property productName() As String
            Get
                Return ResourceManager.GetString("productName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Type.
        '''</summary>
        Friend Shared ReadOnly Property producttype() As String
            Get
                Return ResourceManager.GetString("producttype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty.
        '''</summary>
        Friend Shared ReadOnly Property qty() As String
            Get
                Return ResourceManager.GetString("qty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt.
        '''</summary>
        Friend Shared ReadOnly Property receipt() As String
            Get
                Return ResourceManager.GetString("receipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt No..
        '''</summary>
        Friend Shared ReadOnly Property receiptNo() As String
            Get
                Return ResourceManager.GetString("receiptNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt No..
        '''</summary>
        Friend Shared ReadOnly Property receiptNo1() As String
            Get
                Return ResourceManager.GetString("receiptNo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt.
        '''</summary>
        Friend Shared ReadOnly Property ReceiptProduct() As String
            Get
                Return ResourceManager.GetString("ReceiptProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property save() As String
            Get
                Return ResourceManager.GetString("save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property search() As String
            Get
                Return ResourceManager.GetString("search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seller.
        '''</summary>
        Friend Shared ReadOnly Property seller() As String
            Get
                Return ResourceManager.GetString("seller", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipping Date.
        '''</summary>
        Friend Shared ReadOnly Property ShippingDate() As String
            Get
                Return ResourceManager.GetString("ShippingDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property status() As String
            Get
                Return ResourceManager.GetString("status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stock.
        '''</summary>
        Friend Shared ReadOnly Property stock() As String
            Get
                Return ResourceManager.GetString("stock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub Total.
        '''</summary>
        Friend Shared ReadOnly Property subTotal() As String
            Get
                Return ResourceManager.GetString("subTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Requisition Product.
        '''</summary>
        Friend Shared ReadOnly Property TakeProduct() As String
            Get
                Return ResourceManager.GetString("TakeProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tax ID.
        '''</summary>
        Friend Shared ReadOnly Property TaxID() As String
            Get
                Return ResourceManager.GetString("TaxID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To.
        '''</summary>
        Friend Shared ReadOnly Property todate() As String
            Get
                Return ResourceManager.GetString("todate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend Shared ReadOnly Property total() As String
            Get
                Return ResourceManager.GetString("total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Cost.
        '''</summary>
        Friend Shared ReadOnly Property totalcostvat() As String
            Get
                Return ResourceManager.GetString("totalcostvat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Price.
        '''</summary>
        Friend Shared ReadOnly Property totalPrice() As String
            Get
                Return ResourceManager.GetString("totalPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit.
        '''</summary>
        Friend Shared ReadOnly Property unit() As String
            Get
                Return ResourceManager.GetString("unit", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
