'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class inventory_take_th
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.inventory_take_th", GetType(inventory_take_th).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่.
        '''</summary>
        Friend Shared ReadOnly Property _date() As String
            Get
                Return ResourceManager.GetString("date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ถึงวันที่.
        '''</summary>
        Friend Shared ReadOnly Property _to() As String
            Get
                Return ResourceManager.GetString("to", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เพิ่มรายการ.
        '''</summary>
        Friend Shared ReadOnly Property addItem() As String
            Get
                Return ResourceManager.GetString("addItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เมื่อกรอกข้อมูลเรียบร้อยแล้วกรุณากดปุ่มนี้.
        '''</summary>
        Friend Shared ReadOnly Property Afterfillingout() As String
            Get
                Return ResourceManager.GetString("Afterfillingout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวน.
        '''</summary>
        Friend Shared ReadOnly Property amount() As String
            Get
                Return ResourceManager.GetString("amount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวนที่เหลือ.
        '''</summary>
        Friend Shared ReadOnly Property balance() As String
            Get
                Return ResourceManager.GetString("balance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (ไม่สามารถกรอกข้อมูลได้).
        '''</summary>
        Friend Shared ReadOnly Property Canfillout() As String
            Get
                Return ResourceManager.GetString("Canfillout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เพิ่มสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property clearTExt() As String
            Get
                Return ResourceManager.GetString("clearTExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ต้นทุน/หน่วย.
        '''</summary>
        Friend Shared ReadOnly Property costperunit() As String
            Get
                Return ResourceManager.GetString("costperunit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ลบข้อมูล.
        '''</summary>
        Friend Shared ReadOnly Property del() As String
            Get
                Return ResourceManager.GetString("del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายละเอียด.
        '''</summary>
        Friend Shared ReadOnly Property detail() As String
            Get
                Return ResourceManager.GetString("detail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รหัสสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property prodcutCode() As String
            Get
                Return ResourceManager.GetString("prodcutCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ชื่อสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property productName() As String
            Get
                Return ResourceManager.GetString("productName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่เบิก.
        '''</summary>
        Friend Shared ReadOnly Property requisitionDate() As String
            Get
                Return ResourceManager.GetString("requisitionDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เลขที่ใบเบิกสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property requisitionNo() As String
            Get
                Return ResourceManager.GetString("requisitionNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หัวข้อการเบิก.
        '''</summary>
        Friend Shared ReadOnly Property requisitionTitle() As String
            Get
                Return ResourceManager.GetString("requisitionTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประเภทการเบิก.
        '''</summary>
        Friend Shared ReadOnly Property requisitionType() As String
            Get
                Return ResourceManager.GetString("requisitionType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บันทึก.
        '''</summary>
        Friend Shared ReadOnly Property save() As String
            Get
                Return ResourceManager.GetString("save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สถานะ.
        '''</summary>
        Friend Shared ReadOnly Property status() As String
            Get
                Return ResourceManager.GetString("status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ค้นหา.
        '''</summary>
        Friend Shared ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประเภท.
        '''</summary>
        Friend Shared ReadOnly Property String2() As String
            Get
                Return ResourceManager.GetString("String2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ราคารวม.
        '''</summary>
        Friend Shared ReadOnly Property total() As String
            Get
                Return ResourceManager.GetString("total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ต้นทุนรวม.
        '''</summary>
        Friend Shared ReadOnly Property totalCost() As String
            Get
                Return ResourceManager.GetString("totalCost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หน่วย.
        '''</summary>
        Friend Shared ReadOnly Property unit() As String
            Get
                Return ResourceManager.GetString("unit", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
