'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class item_en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.item_en", GetType(item_en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear Textbox.
        '''</summary>
        Friend Shared ReadOnly Property addProduct() As String
            Get
                Return ResourceManager.GetString("addProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Discount.
        '''</summary>
        Friend Shared ReadOnly Property allowDiscount() As String
            Get
                Return ResourceManager.GetString("allowDiscount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Point.
        '''</summary>
        Friend Shared ReadOnly Property allowPoint() As String
            Get
                Return ResourceManager.GetString("allowPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Promotion.
        '''</summary>
        Friend Shared ReadOnly Property allowpromotion() As String
            Get
                Return ResourceManager.GetString("allowpromotion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Stock.
        '''</summary>
        Friend Shared ReadOnly Property allowStock() As String
            Get
                Return ResourceManager.GetString("allowStock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Button Color.
        '''</summary>
        Friend Shared ReadOnly Property buttonColor() As String
            Get
                Return ResourceManager.GetString("buttonColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category Product.
        '''</summary>
        Friend Shared ReadOnly Property categoryProduct() As String
            Get
                Return ResourceManager.GetString("categoryProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category Selection.
        '''</summary>
        Friend Shared ReadOnly Property categorySelection() As String
            Get
                Return ResourceManager.GetString("categorySelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category Topping.
        '''</summary>
        Friend Shared ReadOnly Property categoryTopping() As String
            Get
                Return ResourceManager.GetString("categoryTopping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code.
        '''</summary>
        Friend Shared ReadOnly Property code() As String
            Get
                Return ResourceManager.GetString("code", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom Price.
        '''</summary>
        Friend Shared ReadOnly Property customPrice() As String
            Get
                Return ResourceManager.GetString("customPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property del() As String
            Get
                Return ResourceManager.GetString("del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove.
        '''</summary>
        Friend Shared ReadOnly Property delProduct() As String
            Get
                Return ResourceManager.GetString("delProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image.
        '''</summary>
        Friend Shared ReadOnly Property Image() As String
            Get
                Return ResourceManager.GetString("Image", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Material.
        '''</summary>
        Friend Shared ReadOnly Property material() As String
            Get
                Return ResourceManager.GetString("material", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to More.
        '''</summary>
        Friend Shared ReadOnly Property more() As String
            Get
                Return ResourceManager.GetString("more", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Kiosk.
        '''</summary>
        Friend Shared ReadOnly Property onKiosk() As String
            Get
                Return ResourceManager.GetString("onKiosk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active POS.
        '''</summary>
        Friend Shared ReadOnly Property onPos() As String
            Get
                Return ResourceManager.GetString("onPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Point To Redeem.
        '''</summary>
        Friend Shared ReadOnly Property pointRedeem() As String
            Get
                Return ResourceManager.GetString("pointRedeem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price.
        '''</summary>
        Friend Shared ReadOnly Property price() As String
            Get
                Return ResourceManager.GetString("price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product.
        '''</summary>
        Friend Shared ReadOnly Property product() As String
            Get
                Return ResourceManager.GetString("product", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Code.
        '''</summary>
        Friend Shared ReadOnly Property productCode() As String
            Get
                Return ResourceManager.GetString("productCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Detail.
        '''</summary>
        Friend Shared ReadOnly Property productDetail() As String
            Get
                Return ResourceManager.GetString("productDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Name.
        '''</summary>
        Friend Shared ReadOnly Property productName() As String
            Get
                Return ResourceManager.GetString("productName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Name 2.
        '''</summary>
        Friend Shared ReadOnly Property productName2() As String
            Get
                Return ResourceManager.GetString("productName2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Name.
        '''</summary>
        Friend Shared ReadOnly Property productNames() As String
            Get
                Return ResourceManager.GetString("productNames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty.
        '''</summary>
        Friend Shared ReadOnly Property qty() As String
            Get
                Return ResourceManager.GetString("qty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property save() As String
            Get
                Return ResourceManager.GetString("save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property search() As String
            Get
                Return ResourceManager.GetString("search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Font Color.
        '''</summary>
        Friend Shared ReadOnly Property textColor() As String
            Get
                Return ResourceManager.GetString("textColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit.
        '''</summary>
        Friend Shared ReadOnly Property unit() As String
            Get
                Return ResourceManager.GetString("unit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit PO.
        '''</summary>
        Friend Shared ReadOnly Property unitPO() As String
            Get
                Return ResourceManager.GetString("unitPO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit PO2.
        '''</summary>
        Friend Shared ReadOnly Property unitPO2() As String
            Get
                Return ResourceManager.GetString("unitPO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vat.
        '''</summary>
        Friend Shared ReadOnly Property vat() As String
            Get
                Return ResourceManager.GetString("vat", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
