'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class main_th
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.main_th", GetType(main_th).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ปิดกะ.
        '''</summary>
        Friend Shared ReadOnly Property closeship() As String
            Get
                Return ResourceManager.GetString("closeship", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สมาชิก.
        '''</summary>
        Friend Shared ReadOnly Property customer() As String
            Get
                Return ResourceManager.GetString("customer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to พนักงาน.
        '''</summary>
        Friend Shared ReadOnly Property employee() As String
            Get
                Return ResourceManager.GetString("employee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กลุ่มสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property groupproduct() As String
            Get
                Return ResourceManager.GetString("groupproduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ออกจากระบบ.
        '''</summary>
        Friend Shared ReadOnly Property logout() As String
            Get
                Return ResourceManager.GetString("logout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ขายสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property pos() As String
            Get
                Return ResourceManager.GetString("pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สินค้า.
        '''</summary>
        Friend Shared ReadOnly Property product() As String
            Get
                Return ResourceManager.GetString("product", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to โปรโมชั่น.
        '''</summary>
        Friend Shared ReadOnly Property promotion() As String
            Get
                Return ResourceManager.GetString("promotion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วัตถุดิบ.
        '''</summary>
        Friend Shared ReadOnly Property rawmaterial() As String
            Get
                Return ResourceManager.GetString("rawmaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงาน.
        '''</summary>
        Friend Shared ReadOnly Property report() As String
            Get
                Return ResourceManager.GetString("report", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ค้นบิล.
        '''</summary>
        Friend Shared ReadOnly Property searchbill() As String
            Get
                Return ResourceManager.GetString("searchbill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ตั้งค่า.
        '''</summary>
        Friend Shared ReadOnly Property setting() As String
            Get
                Return ResourceManager.GetString("setting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สต๊อก.
        '''</summary>
        Friend Shared ReadOnly Property stock() As String
            Get
                Return ResourceManager.GetString("stock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to โต๊ะ/โซน.
        '''</summary>
        Friend Shared ReadOnly Property tablezone() As String
            Get
                Return ResourceManager.GetString("tablezone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ป้ายราคา.
        '''</summary>
        Friend Shared ReadOnly Property tag() As String
            Get
                Return ResourceManager.GetString("tag", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
