'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class pos_payment_th
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.pos_payment_th", GetType(pos_payment_th).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวนเงิน.
        '''</summary>
        Friend Shared ReadOnly Property amounts() As String
            Get
                Return ResourceManager.GetString("amounts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เงินสด.
        '''</summary>
        Friend Shared ReadOnly Property cash() As String
            Get
                Return ResourceManager.GetString("cash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บัตรเงินสด.
        '''</summary>
        Friend Shared ReadOnly Property cashCard() As String
            Get
                Return ResourceManager.GetString("cashCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยืนยันการชำระเงิน.
        '''</summary>
        Friend Shared ReadOnly Property confirm() As String
            Get
                Return ResourceManager.GetString("confirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คูปอง.
        '''</summary>
        Friend Shared ReadOnly Property coupon() As String
            Get
                Return ResourceManager.GetString("coupon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บัตรเครดิต.
        '''</summary>
        Friend Shared ReadOnly Property creditCard() As String
            Get
                Return ResourceManager.GetString("creditCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จ่ายพอดี.
        '''</summary>
        Friend Shared ReadOnly Property exact() As String
            Get
                Return ResourceManager.GetString("exact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวนเงิน.
        '''</summary>
        Friend Shared ReadOnly Property money() As String
            Get
                Return ResourceManager.GetString("money", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to อื่นๆ.
        '''</summary>
        Friend Shared ReadOnly Property other() As String
            Get
                Return ResourceManager.GetString("other", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ชำระเงิน.
        '''</summary>
        Friend Shared ReadOnly Property payment() As String
            Get
                Return ResourceManager.GetString("payment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประเภทการชำระเงิน.
        '''</summary>
        Friend Shared ReadOnly Property paymentType() As String
            Get
                Return ResourceManager.GetString("paymentType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ปุ่มด่วน.
        '''</summary>
        Friend Shared ReadOnly Property quickbutton() As String
            Get
                Return ResourceManager.GetString("quickbutton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ลบการชำระเงิน.
        '''</summary>
        Friend Shared ReadOnly Property remove() As String
            Get
                Return ResourceManager.GetString("remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เลือกการรับชำระ.
        '''</summary>
        Friend Shared ReadOnly Property selectPayment() As String
            Get
                Return ResourceManager.GetString("selectPayment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยอดรับชำระ.
        '''</summary>
        Friend Shared ReadOnly Property total() As String
            Get
                Return ResourceManager.GetString("total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยอดที่ต้องชำระ.
        '''</summary>
        Friend Shared ReadOnly Property totalpaid() As String
            Get
                Return ResourceManager.GetString("totalpaid", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
