'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class pos_Th
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.pos_Th", GetType(pos_Th).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวน.
        '''</summary>
        Friend Shared ReadOnly Property amount() As String
            Get
                Return ResourceManager.GetString("amount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บาร์โค้ด.
        '''</summary>
        Friend Shared ReadOnly Property barcode() As String
            Get
                Return ResourceManager.GetString("barcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยกเลิกการขาย.
        '''</summary>
        Friend Shared ReadOnly Property cancelBill() As String
            Get
                Return ResourceManager.GetString("cancelBill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หมวดสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property category() As String
            Get
                Return ResourceManager.GetString("category", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ค่าใช้จ่าย.
        '''</summary>
        Friend Shared ReadOnly Property costing() As String
            Get
                Return ResourceManager.GetString("costing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สมาชิก.
        '''</summary>
        Friend Shared ReadOnly Property customer() As String
            Get
                Return ResourceManager.GetString("customer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เช็คยอดระหว่างวัน.
        '''</summary>
        Friend Shared ReadOnly Property daily() As String
            Get
                Return ResourceManager.GetString("daily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ส่วนลด :.
        '''</summary>
        Friend Shared ReadOnly Property discount() As String
            Get
                Return ResourceManager.GetString("discount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ส่วนลด ฿.
        '''</summary>
        Friend Shared ReadOnly Property discountBath() As String
            Get
                Return ResourceManager.GetString("discountBath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ส่วนลด %.
        '''</summary>
        Friend Shared ReadOnly Property discountPercent() As String
            Get
                Return ResourceManager.GetString("discountPercent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รวมโต๊ะ.
        '''</summary>
        Friend Shared ReadOnly Property groupTable() As String
            Get
                Return ResourceManager.GetString("groupTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ใบแจ้งยอด.
        '''</summary>
        Friend Shared ReadOnly Property Invoice() As String
            Get
                Return ResourceManager.GetString("Invoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายการ.
        '''</summary>
        Friend Shared ReadOnly Property list() As String
            Get
                Return ResourceManager.GetString("list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ย้ายโต๊ะ.
        '''</summary>
        Friend Shared ReadOnly Property moveTable() As String
            Get
                Return ResourceManager.GetString("moveTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ชำระเงิน.
        '''</summary>
        Friend Shared ReadOnly Property payment() As String
            Get
                Return ResourceManager.GetString("payment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ใช้แต้มสะสม.
        '''</summary>
        Friend Shared ReadOnly Property point() As String
            Get
                Return ResourceManager.GetString("point", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ขายสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property POS() As String
            Get
                Return ResourceManager.GetString("POS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สินค้า.
        '''</summary>
        Friend Shared ReadOnly Property product() As String
            Get
                Return ResourceManager.GetString("product", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวน.
        '''</summary>
        Friend Shared ReadOnly Property qty() As String
            Get
                Return ResourceManager.GetString("qty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บันทึก.
        '''</summary>
        Friend Shared ReadOnly Property save() As String
            Get
                Return ResourceManager.GetString("save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายการพักการขาย.
        '''</summary>
        Friend Shared ReadOnly Property saveSale() As String
            Get
                Return ResourceManager.GetString("saveSale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ค้นหา.
        '''</summary>
        Friend Shared ReadOnly Property search() As String
            Get
                Return ResourceManager.GetString("search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to แยกบิล.
        '''</summary>
        Friend Shared ReadOnly Property splitBill() As String
            Get
                Return ResourceManager.GetString("splitBill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รวม :.
        '''</summary>
        Friend Shared ReadOnly Property subTotal() As String
            Get
                Return ResourceManager.GetString("subTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ท็อปปิ้ง.
        '''</summary>
        Friend Shared ReadOnly Property topping() As String
            Get
                Return ResourceManager.GetString("topping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รวมทั้งหมด :.
        '''</summary>
        Friend Shared ReadOnly Property total() As String
            Get
                Return ResourceManager.GetString("total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ราคารวม.
        '''</summary>
        Friend Shared ReadOnly Property totalprice() As String
            Get
                Return ResourceManager.GetString("totalprice", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
