'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class report_en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.report_en", GetType(report_en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Month.
        '''</summary>
        Friend Shared ReadOnly Property month() As String
            Get
                Return ResourceManager.GetString("month", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No..
        '''</summary>
        Friend Shared ReadOnly Property no() As String
            Get
                Return ResourceManager.GetString("no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print.
        '''</summary>
        Friend Shared ReadOnly Property print() As String
            Get
                Return ResourceManager.GetString("print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report.
        '''</summary>
        Friend Shared ReadOnly Property report() As String
            Get
                Return ResourceManager.GetString("report", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report 80mm.
        '''</summary>
        Friend Shared ReadOnly Property report80() As String
            Get
                Return ResourceManager.GetString("report80", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report 80mm (Terminal).
        '''</summary>
        Friend Shared ReadOnly Property report80Terminal() As String
            Get
                Return ResourceManager.GetString("report80Terminal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Cancel Sale.
        '''</summary>
        Friend Shared ReadOnly Property reportCancelSale() As String
            Get
                Return ResourceManager.GetString("reportCancelSale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Close Shift.
        '''</summary>
        Friend Shared ReadOnly Property reportCloseShift() As String
            Get
                Return ResourceManager.GetString("reportCloseShift", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Sale Daliy.
        '''</summary>
        Friend Shared ReadOnly Property reportDaliy() As String
            Get
                Return ResourceManager.GetString("reportDaliy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Expenses.
        '''</summary>
        Friend Shared ReadOnly Property reportExpenses() As String
            Get
                Return ResourceManager.GetString("reportExpenses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Grab Food.
        '''</summary>
        Friend Shared ReadOnly Property reportGrab() As String
            Get
                Return ResourceManager.GetString("reportGrab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report LINE MAN.
        '''</summary>
        Friend Shared ReadOnly Property reportLine() As String
            Get
                Return ResourceManager.GetString("reportLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Material.
        '''</summary>
        Friend Shared ReadOnly Property reportMaterial() As String
            Get
                Return ResourceManager.GetString("reportMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Payment Detail.
        '''</summary>
        Friend Shared ReadOnly Property reportPaymentDetail() As String
            Get
                Return ResourceManager.GetString("reportPaymentDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Product.
        '''</summary>
        Friend Shared ReadOnly Property reportProduct() As String
            Get
                Return ResourceManager.GetString("reportProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Profit.
        '''</summary>
        Friend Shared ReadOnly Property reportProfit() As String
            Get
                Return ResourceManager.GetString("reportProfit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report RobinHood.
        '''</summary>
        Friend Shared ReadOnly Property reportRobin() As String
            Get
                Return ResourceManager.GetString("reportRobin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Sale (Category).
        '''</summary>
        Friend Shared ReadOnly Property reportSaleCategory() As String
            Get
                Return ResourceManager.GetString("reportSaleCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Sale (Customer).
        '''</summary>
        Friend Shared ReadOnly Property reportSaleCustomer() As String
            Get
                Return ResourceManager.GetString("reportSaleCustomer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Sale (Day).
        '''</summary>
        Friend Shared ReadOnly Property reportsaleDay() As String
            Get
                Return ResourceManager.GetString("reportsaleDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Sale (Sale No.).
        '''</summary>
        Friend Shared ReadOnly Property reportSaleNo() As String
            Get
                Return ResourceManager.GetString("reportSaleNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Sale (Detail).
        '''</summary>
        Friend Shared ReadOnly Property reportSaleNoDetail() As String
            Get
                Return ResourceManager.GetString("reportSaleNoDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Sale (Payment).
        '''</summary>
        Friend Shared ReadOnly Property reportSalePayment() As String
            Get
                Return ResourceManager.GetString("reportSalePayment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Shopee.
        '''</summary>
        Friend Shared ReadOnly Property reportShopee() As String
            Get
                Return ResourceManager.GetString("reportShopee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Stock.
        '''</summary>
        Friend Shared ReadOnly Property reportStock() As String
            Get
                Return ResourceManager.GetString("reportStock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Topping.
        '''</summary>
        Friend Shared ReadOnly Property reportTopping() As String
            Get
                Return ResourceManager.GetString("reportTopping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Top Sale.
        '''</summary>
        Friend Shared ReadOnly Property reportTopSale() As String
            Get
                Return ResourceManager.GetString("reportTopSale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Vat.
        '''</summary>
        Friend Shared ReadOnly Property reportVat() As String
            Get
                Return ResourceManager.GetString("reportVat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send.
        '''</summary>
        Friend Shared ReadOnly Property send() As String
            Get
                Return ResourceManager.GetString("send", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send Report / Print.
        '''</summary>
        Friend Shared ReadOnly Property sendEmail() As String
            Get
                Return ResourceManager.GetString("sendEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send Report  / Month.
        '''</summary>
        Friend Shared ReadOnly Property sendEmailMonth() As String
            Get
                Return ResourceManager.GetString("sendEmailMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year.
        '''</summary>
        Friend Shared ReadOnly Property year() As String
            Get
                Return ResourceManager.GetString("year", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
