'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class settingSystem_en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iEasyPOS.settingSystem_en", GetType(settingSystem_en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Print.
        '''</summary>
        Friend Shared ReadOnly Property allowPrint() As String
            Get
                Return ResourceManager.GetString("allowPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow PrintOrder.
        '''</summary>
        Friend Shared ReadOnly Property allowPrintOrder() As String
            Get
                Return ResourceManager.GetString("allowPrintOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Footer.
        '''</summary>
        Friend Shared ReadOnly Property bottom() As String
            Get
                Return ResourceManager.GetString("bottom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Footer 2.
        '''</summary>
        Friend Shared ReadOnly Property bottom2() As String
            Get
                Return ResourceManager.GetString("bottom2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category height.
        '''</summary>
        Friend Shared ReadOnly Property categoryHeight() As String
            Get
                Return ResourceManager.GetString("categoryHeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy.
        '''</summary>
        Friend Shared ReadOnly Property copy() As String
            Get
                Return ResourceManager.GetString("copy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy Close shift.
        '''</summary>
        Friend Shared ReadOnly Property copyCloseShift() As String
            Get
                Return ResourceManager.GetString("copyCloseShift", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy report close shift.
        '''</summary>
        Friend Shared ReadOnly Property copyReportCloseShift() As String
            Get
                Return ResourceManager.GetString("copyReportCloseShift", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy report sale close shift.
        '''</summary>
        Friend Shared ReadOnly Property copyReportSaleCloseShift() As String
            Get
                Return ResourceManager.GetString("copyReportSaleCloseShift", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Header.
        '''</summary>
        Friend Shared ReadOnly Property header() As String
            Get
                Return ResourceManager.GetString("header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Header 2.
        '''</summary>
        Friend Shared ReadOnly Property header2() As String
            Get
                Return ResourceManager.GetString("header2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to more.
        '''</summary>
        Friend Shared ReadOnly Property more() As String
            Get
                Return ResourceManager.GetString("more", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to POS Setting product button.
        '''</summary>
        Friend Shared ReadOnly Property POSsettingButtonProduct() As String
            Get
                Return ResourceManager.GetString("POSsettingButtonProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product height.
        '''</summary>
        Friend Shared ReadOnly Property productHeight() As String
            Get
                Return ResourceManager.GetString("productHeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rows.
        '''</summary>
        Friend Shared ReadOnly Property rows() As String
            Get
                Return ResourceManager.GetString("rows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property save() As String
            Get
                Return ResourceManager.GetString("save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setting Button POS.
        '''</summary>
        Friend Shared ReadOnly Property settingButtonProduct() As String
            Get
                Return ResourceManager.GetString("settingButtonProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setting Printer Receipt.
        '''</summary>
        Friend Shared ReadOnly Property settingPrinterReceipt() As String
            Get
                Return ResourceManager.GetString("settingPrinterReceipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setting Receipt.
        '''</summary>
        Friend Shared ReadOnly Property settingReceipt() As String
            Get
                Return ResourceManager.GetString("settingReceipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show image product.
        '''</summary>
        Friend Shared ReadOnly Property showImageProduct() As String
            Get
                Return ResourceManager.GetString("showImageProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Table system.
        '''</summary>
        Friend Shared ReadOnly Property tablesystem() As String
            Get
                Return ResourceManager.GetString("tablesystem", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
