Public Class ItemData
    Public ItemId As Integer?
    Public ItemCode As String
    Public ItemName As String
    Public ItemName2 As String
    Public Notes As String
    Public Notes2 As String
    Public CategoryId As Integer?
    Public CategoryId2 As Integer?
    Public CategoryId3 As Integer?
    Public CategoryId4 As Integer?
    Public CategoryGroupId As Integer?
    Public CategoryPakgeId As Integer?
    Public SupplierId As Integer?
    Public ImageText As String
    Public Active As Boolean?
    Public InsertDate As String
    Public UpdateDate As String
    Public UserId As Integer?
    Public DeleteDate As String
    Public DeleteUserId As Integer?
    Public IsTrackStock As Integer?
    Public USUnitId As Integer?
    Public POUnitId As Integer?
    Public POUnitId2 As Integer?
    Public ItemStatusId As Integer?
    Public AllowDC As Boolean?
    Public MaxPercentDC As Decimal?
    Public AllowRedeemPoint As Boolean?
    Public PointToRedeem As Integer?
    Public IsRecommended As Boolean?
    Public IsCanDelivery As Boolean?
    Public IsTakeTime As Boolean?
    Public IsOnSeason As Boolean?
    Public IsTraddingItem As Boolean?
    Public IsWeight As Boolean?
    Public IsPromotion As Boolean?
    Public IsPackage As Boolean?
    Public ItemCost As Decimal?
    Public ItemPrice As Decimal?
    Public PrinterName As String
    Public ButtonColor As Integer?
    Public FontColor As Integer?
    Public IsVatChecked As Boolean?
    Public TaxId As Integer?
    Public IsActive As Boolean?
    Public OrderTypeId As Integer?
    Public OrderOfferId As Integer?
    Public TimeSend As Integer?
    Public IsAlertInventory As Boolean?
    Public TypeCateItemId As Integer?
    Public ItemKiOsk As Boolean?
End Class
