Public Class UsersModel
    Public UserId As Integer?
    Public FirstName As String
    Public LastName As String
    Public Passwords As String
    Public BirthDay As String
    Public Email As String
    Public Active_Email As Boolean?
    Public Hash As String
    Public Pin As String
    Public QRcode As String
    Public Phone As String
    Public RegisterDate As String
    Public Active As Boolean?
    Public Staff_Active As Boolean?
    Public UpdateDate As String
    Public Deletedate As String
    Public DeleteUserId As Integer?
    Public RoleId As String
    Public Nickname As String
    Public CardId As String
    Public GenderId As Integer?
    Public NationalityId As Integer?
    Public Address As String
    Public Image As String
    Public PositionId As String
    Public UserPayType As String
    Public Phone2 As String
    Public Phone3 As String
    Public WorkStartDate As String
    Public Pay As Decimal?
    Public PayTypeId As Integer?
    Public OverTimePay As Decimal?
    Public OverTimePayTypeId As Integer?
    Public Diligence As Decimal?
    Public DiligenceTypeId As Integer?
    Public BreakId As Integer?
    Public WorkTypeId As Integer?
    Public BranchId As Integer?
    Public EditUserId As Integer?
End Class
